language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

notifications:
  email: false

install:
  - pip install -e .[testing]
  - pip install coveralls

script: nosetests --with-coverage --cover-package=smelli

after_success: coveralls
